//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossStitchCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DMCColours {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DMCColours() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossStitchCreator.DMCColours", typeof(DMCColours).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floss#,Description,Red,Green,Blue,RGB code,Row
        ///3713,Salmon Very Light,255,226,226,FFE2E2,row 01-01
        ///761,Salmon Light,255,201,201,FFC9C9,row 01-02
        ///760,Salmon,245,173,173,F5ADAD,row 01-03
        ///3712,Salmon Medium,241,135,135,F18787,row 01-04
        ///3328,Salmon Dark,227,109,109,E36D6D,row 01-05
        ///347,Salmon Very Dark,191,45,45,BF2D2D,row 01-06
        ///353,Peach,254,215,204,FED7CC,row 01-07
        ///352,Coral Light,253,156,151,FD9C97,row 01-08
        ///351,Coral,233,106,103,E96A67,row 01-09
        ///350,Coral Medium,224,72,72,E04848,row 01-10
        ///349,Cor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DmcToRgb {
            get {
                return ResourceManager.GetString("DmcToRgb", resourceCulture);
            }
        }
    }
}
